[package]
name = "bitcoin-frost-wallet"
version = "0.1.0"
edition = "2021"
description = "FROST/ChillDKG implementation for Bitcoin wallets"

[dependencies]
secp256k1 = { version = "0.27", features = ["rand", "rand-std"] }
bitcoin = "0.31"
rand = "0.8"
sha2 = "0.10"
thiserror = "1.0"

[dev-dependencies]
hex = "0.4"
test-case = "3.3"

[features]
default = ["std"]
std = ["secp256k1/std"]
parallel = ["rayon"]